export type AnatomyView = 'front' | 'back';

export type MuscleHeadRegion = {
  id: string;
  muscle: string;
  head: string;
  label: string;
  view: AnatomyView;
  mirrored: boolean;
  centerX: number;
  centerY: number;
  rx: number;
  ry: number;
  rotate: number;
  summary: string;
  primaryAction: string;
};

export const ANATOMY_CANVAS = {
  width: 420,
  height: 760
} as const;

export const MUSCLE_HEAD_REGIONS: MuscleHeadRegion[] = [
  {
    id: 'deltoid_anterior',
    muscle: 'Deltoid',
    head: 'Anterior head',
    label: 'Deltoid - Anterior head',
    view: 'front',
    mirrored: true,
    centerX: 128,
    centerY: 170,
    rx: 24,
    ry: 38,
    rotate: -24,
    summary: 'Front deltoid fibers that bias shoulder flexion and internal rotation.',
    primaryAction: 'Shoulder flexion'
  },
  {
    id: 'pectoralis_major_clavicular',
    muscle: 'Pectoralis major',
    head: 'Clavicular head',
    label: 'Pectoralis major - Clavicular head',
    view: 'front',
    mirrored: true,
    centerX: 150,
    centerY: 198,
    rx: 30,
    ry: 36,
    rotate: -24,
    summary: 'Upper chest fibers with stronger shoulder flexion emphasis.',
    primaryAction: 'Shoulder flexion + horizontal adduction'
  },
  {
    id: 'pectoralis_major_sternal',
    muscle: 'Pectoralis major',
    head: 'Sternal head',
    label: 'Pectoralis major - Sternal head',
    view: 'front',
    mirrored: true,
    centerX: 158,
    centerY: 246,
    rx: 33,
    ry: 44,
    rotate: -14,
    summary: 'Mid/lower chest fibers with higher adduction and pressing contribution.',
    primaryAction: 'Shoulder adduction + horizontal adduction'
  },
  {
    id: 'biceps_brachii_long_head',
    muscle: 'Biceps brachii',
    head: 'Long head',
    label: 'Biceps brachii - Long head',
    view: 'front',
    mirrored: true,
    centerX: 117,
    centerY: 265,
    rx: 16,
    ry: 52,
    rotate: -16,
    summary: 'Lateral biceps head, often stressed in incline and supinated curl patterns.',
    primaryAction: 'Elbow flexion + forearm supination'
  },
  {
    id: 'biceps_brachii_short_head',
    muscle: 'Biceps brachii',
    head: 'Short head',
    label: 'Biceps brachii - Short head',
    view: 'front',
    mirrored: true,
    centerX: 133,
    centerY: 268,
    rx: 14,
    ry: 48,
    rotate: -8,
    summary: 'Medial biceps head, frequently emphasized by close-grip and preacher variants.',
    primaryAction: 'Elbow flexion + shoulder flexion support'
  },
  {
    id: 'brachialis',
    muscle: 'Brachialis',
    head: 'Deep head',
    label: 'Brachialis - Deep head',
    view: 'front',
    mirrored: true,
    centerX: 123,
    centerY: 332,
    rx: 14,
    ry: 26,
    rotate: -8,
    summary: 'Deep elbow flexor underneath the biceps with high leverage in neutral grips.',
    primaryAction: 'Elbow flexion'
  },
  {
    id: 'forearm_flexor_group',
    muscle: 'Forearm flexor group',
    head: 'Anterior compartment',
    label: 'Forearm flexor group - Anterior compartment',
    view: 'front',
    mirrored: true,
    centerX: 116,
    centerY: 390,
    rx: 18,
    ry: 48,
    rotate: -8,
    summary: 'Wrist/finger flexor complex contributing to grip and pulling force transfer.',
    primaryAction: 'Wrist and finger flexion'
  },
  {
    id: 'external_oblique',
    muscle: 'External oblique',
    head: 'Anterior-lateral fibers',
    label: 'External oblique - Anterior-lateral fibers',
    view: 'front',
    mirrored: true,
    centerX: 156,
    centerY: 322,
    rx: 24,
    ry: 48,
    rotate: -20,
    summary: 'Lateral trunk fibers aiding anti-rotation, bracing, and trunk flexion.',
    primaryAction: 'Trunk rotation + anti-rotation'
  },
  {
    id: 'rectus_abdominis_upper',
    muscle: 'Rectus abdominis',
    head: 'Upper segment',
    label: 'Rectus abdominis - Upper segment',
    view: 'front',
    mirrored: false,
    centerX: 210,
    centerY: 300,
    rx: 38,
    ry: 42,
    rotate: 0,
    summary: 'Upper anterior core segment, often loaded in trunk flexion tasks.',
    primaryAction: 'Spinal flexion + bracing'
  },
  {
    id: 'rectus_abdominis_lower',
    muscle: 'Rectus abdominis',
    head: 'Lower segment',
    label: 'Rectus abdominis - Lower segment',
    view: 'front',
    mirrored: false,
    centerX: 210,
    centerY: 360,
    rx: 34,
    ry: 40,
    rotate: 0,
    summary: 'Lower anterior core segment supporting pelvic control and bracing.',
    primaryAction: 'Posterior pelvic tilt + trunk bracing'
  },
  {
    id: 'adductor_longus',
    muscle: 'Adductor longus',
    head: 'Medial thigh fibers',
    label: 'Adductor longus - Medial thigh fibers',
    view: 'front',
    mirrored: true,
    centerX: 176,
    centerY: 488,
    rx: 20,
    ry: 56,
    rotate: 6,
    summary: 'Primary medial thigh adductor with stabilizing role in gait and stance.',
    primaryAction: 'Hip adduction'
  },
  {
    id: 'rectus_femoris',
    muscle: 'Quadriceps',
    head: 'Rectus femoris',
    label: 'Quadriceps - Rectus femoris',
    view: 'front',
    mirrored: true,
    centerX: 188,
    centerY: 530,
    rx: 20,
    ry: 74,
    rotate: 4,
    summary: 'Biarticular quad head crossing hip and knee; key in sprint and jump mechanics.',
    primaryAction: 'Knee extension + hip flexion'
  },
  {
    id: 'vastus_lateralis',
    muscle: 'Quadriceps',
    head: 'Vastus lateralis',
    label: 'Quadriceps - Vastus lateralis',
    view: 'front',
    mirrored: true,
    centerX: 156,
    centerY: 540,
    rx: 22,
    ry: 82,
    rotate: -8,
    summary: 'Lateral quad head with high contribution to forceful knee extension.',
    primaryAction: 'Knee extension'
  },
  {
    id: 'vastus_medialis',
    muscle: 'Quadriceps',
    head: 'Vastus medialis',
    label: 'Quadriceps - Vastus medialis',
    view: 'front',
    mirrored: true,
    centerX: 196,
    centerY: 572,
    rx: 20,
    ry: 58,
    rotate: 12,
    summary: 'Medial quad head supporting terminal knee extension and patellar tracking.',
    primaryAction: 'Knee extension + patellar stabilization'
  },
  {
    id: 'tibialis_anterior',
    muscle: 'Tibialis anterior',
    head: 'Anterior shin fibers',
    label: 'Tibialis anterior - Anterior shin fibers',
    view: 'front',
    mirrored: true,
    centerX: 186,
    centerY: 670,
    rx: 14,
    ry: 62,
    rotate: 6,
    summary: 'Primary dorsiflexor that controls foot clearance and eccentric landing.',
    primaryAction: 'Ankle dorsiflexion'
  },
  {
    id: 'deltoid_posterior',
    muscle: 'Deltoid',
    head: 'Posterior head',
    label: 'Deltoid - Posterior head',
    view: 'back',
    mirrored: true,
    centerX: 130,
    centerY: 174,
    rx: 25,
    ry: 40,
    rotate: -22,
    summary: 'Rear deltoid fibers that bias horizontal abduction and shoulder extension.',
    primaryAction: 'Shoulder extension + horizontal abduction'
  },
  {
    id: 'trapezius_upper',
    muscle: 'Trapezius',
    head: 'Upper fibers',
    label: 'Trapezius - Upper fibers',
    view: 'back',
    mirrored: true,
    centerX: 176,
    centerY: 152,
    rx: 34,
    ry: 36,
    rotate: -18,
    summary: 'Upper trap fibers controlling scapular elevation and upward rotation.',
    primaryAction: 'Scapular elevation'
  },
  {
    id: 'trapezius_middle',
    muscle: 'Trapezius',
    head: 'Middle fibers',
    label: 'Trapezius - Middle fibers',
    view: 'back',
    mirrored: true,
    centerX: 180,
    centerY: 220,
    rx: 28,
    ry: 34,
    rotate: -15,
    summary: 'Middle trap fibers supporting scapular retraction and posture control.',
    primaryAction: 'Scapular retraction'
  },
  {
    id: 'latissimus_dorsi',
    muscle: 'Latissimus dorsi',
    head: 'Thoracolumbar fibers',
    label: 'Latissimus dorsi - Thoracolumbar fibers',
    view: 'back',
    mirrored: true,
    centerX: 165,
    centerY: 292,
    rx: 30,
    ry: 74,
    rotate: -18,
    summary: 'Large posterior pulling complex driving shoulder adduction and extension.',
    primaryAction: 'Shoulder extension + adduction'
  },
  {
    id: 'triceps_long_head',
    muscle: 'Triceps brachii',
    head: 'Long head',
    label: 'Triceps brachii - Long head',
    view: 'back',
    mirrored: true,
    centerX: 118,
    centerY: 278,
    rx: 16,
    ry: 56,
    rotate: -14,
    summary: 'Biarticular triceps head supporting elbow extension and shoulder extension.',
    primaryAction: 'Elbow extension'
  },
  {
    id: 'triceps_lateral_head',
    muscle: 'Triceps brachii',
    head: 'Lateral head',
    label: 'Triceps brachii - Lateral head',
    view: 'back',
    mirrored: true,
    centerX: 132,
    centerY: 286,
    rx: 14,
    ry: 50,
    rotate: -8,
    summary: 'Lateral triceps fibers with high force production in pressing lockout.',
    primaryAction: 'Elbow extension'
  },
  {
    id: 'triceps_medial_head',
    muscle: 'Triceps brachii',
    head: 'Medial head',
    label: 'Triceps brachii - Medial head',
    view: 'back',
    mirrored: true,
    centerX: 124,
    centerY: 336,
    rx: 12,
    ry: 28,
    rotate: -8,
    summary: 'Deep triceps fibers with strong contribution in controlled elbow extension.',
    primaryAction: 'Elbow extension'
  },
  {
    id: 'erector_spinae',
    muscle: 'Erector spinae',
    head: 'Lumbar columns',
    label: 'Erector spinae - Lumbar columns',
    view: 'back',
    mirrored: true,
    centerX: 192,
    centerY: 318,
    rx: 16,
    ry: 92,
    rotate: 0,
    summary: 'Posterior spinal columns that resist flexion and maintain trunk extension.',
    primaryAction: 'Spinal extension + anti-flexion'
  },
  {
    id: 'gluteus_medius',
    muscle: 'Gluteus medius',
    head: 'Superior-lateral fibers',
    label: 'Gluteus medius - Superior-lateral fibers',
    view: 'back',
    mirrored: true,
    centerX: 170,
    centerY: 404,
    rx: 24,
    ry: 34,
    rotate: -14,
    summary: 'Primary hip abductor and frontal-plane stabilizer in gait.',
    primaryAction: 'Hip abduction + pelvic stability'
  },
  {
    id: 'gluteus_maximus',
    muscle: 'Gluteus maximus',
    head: 'Posterior fibers',
    label: 'Gluteus maximus - Posterior fibers',
    view: 'back',
    mirrored: true,
    centerX: 172,
    centerY: 460,
    rx: 30,
    ry: 44,
    rotate: -12,
    summary: 'Largest hip extensor driving hinge, sprint, and jump propulsion.',
    primaryAction: 'Hip extension'
  },
  {
    id: 'biceps_femoris_long_head',
    muscle: 'Hamstrings',
    head: 'Biceps femoris long head',
    label: 'Hamstrings - Biceps femoris long head',
    view: 'back',
    mirrored: true,
    centerX: 160,
    centerY: 550,
    rx: 18,
    ry: 74,
    rotate: -10,
    summary: 'Lateral hamstring head assisting hip extension and knee flexion.',
    primaryAction: 'Knee flexion + hip extension'
  },
  {
    id: 'biceps_femoris_short_head',
    muscle: 'Hamstrings',
    head: 'Biceps femoris short head',
    label: 'Hamstrings - Biceps femoris short head',
    view: 'back',
    mirrored: true,
    centerX: 166,
    centerY: 508,
    rx: 14,
    ry: 38,
    rotate: -10,
    summary: 'Short lateral hamstring head acting mainly over the knee joint.',
    primaryAction: 'Knee flexion'
  },
  {
    id: 'semitendinosus',
    muscle: 'Hamstrings',
    head: 'Semitendinosus',
    label: 'Hamstrings - Semitendinosus',
    view: 'back',
    mirrored: true,
    centerX: 188,
    centerY: 548,
    rx: 14,
    ry: 72,
    rotate: 8,
    summary: 'Medial hamstring component supporting hip extension and tibial rotation.',
    primaryAction: 'Knee flexion + hip extension'
  },
  {
    id: 'semimembranosus',
    muscle: 'Hamstrings',
    head: 'Semimembranosus',
    label: 'Hamstrings - Semimembranosus',
    view: 'back',
    mirrored: true,
    centerX: 198,
    centerY: 548,
    rx: 14,
    ry: 68,
    rotate: 12,
    summary: 'Broad medial hamstring head with high posterior-chain stabilization role.',
    primaryAction: 'Knee flexion + hip extension'
  },
  {
    id: 'gastrocnemius_medial_head',
    muscle: 'Gastrocnemius',
    head: 'Medial head',
    label: 'Gastrocnemius - Medial head',
    view: 'back',
    mirrored: true,
    centerX: 190,
    centerY: 668,
    rx: 14,
    ry: 60,
    rotate: 10,
    summary: 'Medial calf head contributing to plantarflexion and propulsion.',
    primaryAction: 'Ankle plantarflexion'
  },
  {
    id: 'gastrocnemius_lateral_head',
    muscle: 'Gastrocnemius',
    head: 'Lateral head',
    label: 'Gastrocnemius - Lateral head',
    view: 'back',
    mirrored: true,
    centerX: 168,
    centerY: 668,
    rx: 14,
    ry: 60,
    rotate: -8,
    summary: 'Lateral calf head assisting elastic recoil and force transfer.',
    primaryAction: 'Ankle plantarflexion'
  },
  {
    id: 'soleus',
    muscle: 'Soleus',
    head: 'Deep calf fibers',
    label: 'Soleus - Deep calf fibers',
    view: 'back',
    mirrored: true,
    centerX: 178,
    centerY: 705,
    rx: 16,
    ry: 46,
    rotate: 2,
    summary: 'Deep postural calf muscle with high endurance demand during stance.',
    primaryAction: 'Ankle plantarflexion + posture support'
  }
];
